In [1]:
!gdown '1ppK1OwQl1CZSHdXapUEyiyetcJ4jW2ES'

Downloading...
From: https://drive.google.com/uc?id=1ppK1OwQl1CZSHdXapUEyiyetcJ4jW2ES
To: /content/data.csv
100% 29.7M/29.7M [00:00<00:00, 54.8MB/s]

In [2]:
import numpy as np
import pandas as pd

In [17]:
# loading the data from the csv file to apandas dataframe
df = pd.read_csv('data.csv')
df.head()

,valence,year,acousticness,artists,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,loudness,mode,name,popularity,release_date,speechiness,tempo
0,0.0594,1921,0.982,"['Sergei Rachmaninoff', 'James Levine', 'Berli...",0.279,831667,0.211,0,4BJqT0PrAfrxzMOxytFOIz,0.878000,10,0.665,-20.096,1,"Piano Concerto No. 3 in D Minor, Op. 30: III. ...",4,1921,0.0366,80.954
1,0.9630,1921,0.732,['Dennis Day'],0.819,180533,0.341,0,7xPhfUan2yNtyFG0cUWkt8,0.000000,7,0.160,-12.441,1,Clancy Lowered the Boom,5,1921,0.4150,60.936
2,0.0394,1921,0.961,['KHP Kridhamardawa Karaton Ngayogyakarta Hadi...,0.328,500062,0.166,0,1o6I8BglA6ylDMrIELygv1,0.913000,3,0.101,-14.850,1,Gati Bali,5,1921,0.0339,110.339
3,0.1650,1921,0.967,['Frank Parker'],0.275,210000,0.309,0,3ftBPsC5vPBKxYSee08FDH,0.000028,5,0.381,-9.316,1,Danny Boy,3,1921,0.0354,100.109
4,0.2530,1921,0.957,['Phil Regan'],0.418,166693,0.193,0,4d6HGyGT8e121BsdKmw9v6,0.000002,3,0.229,-10.096,1,When Irish Eyes Are Smiling,2,1921,0.0380,101.665

In [4]:
df.shape

(170653, 19)

In [18]:
df = df[df['year'] >= 2000]  #taking song only after 2000

In [19]:
df = df[df['popularity'] >= 65] #taking song with popularity score over 65

In [42]:
# resetting the index from 1 t0 ...
df = df.reset_index(drop=True)
df

,valence,year,acousticness,artists,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,loudness,mode,name,popularity,release_date,speechiness,tempo
0,0.285,2000,0.00239,['Coldplay'],0.429,266773,0.661,0,3AJwUDP919kvQ9QcozQPxg,0.000121,11,0.2340,-7.227,1,Yellow,84,2000-07-10,0.0281,173.372
1,0.613,2000,0.14300,['OutKast'],0.843,270507,0.806,1,0I3q5fE6wg7LIfHGngUTnV,0.000000,4,0.0771,-5.946,0,Ms. Jackson,80,2000-10-31,0.2690,94.948
2,0.400,2000,0.00958,['Linkin Park'],0.556,216880,0.864,0,60a0Rd6pjrkxjPbaKzXjfq,0.000000,3,0.2090,-5.870,0,In the End,84,2000-10-24,0.0584,105.143
3,0.543,2000,0.00664,['3 Doors Down'],0.545,233933,0.865,0,6ZOBP3NvffbU4SZcrnt1k6,0.000011,11,0.1680,-5.708,0,Kryptonite,78,2000,0.0286,99.009
4,0.760,2000,0.03020,['Eminem'],0.949,284200,0.661,1,3yfqSUWxFvZELEM4PmlwIR,0.000000,5,0.0454,-4.244,0,The Real Slim Shady,80,2000-05-23,0.0572,104.504
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8345,0.608,2020,0.08460,"['Anuel AA', 'Daddy Yankee', 'KAROL G', 'Ozuna...",0.786,301714,0.808,0,0KkIkfsLEJbrcIhYsCL7L5,0.000289,7,0.0822,-3.702,1,China,72,2020-05-29,0.0881,105.029
8346,0.734,2020,0.20600,['Ashnikko'],0.717,150654,0.753,0,0OStKKAuXlxA0fMH54Qs6E,0.000000,7,0.1010,-6.020,1,Halloweenie III: Seven Days,68,2020-10-23,0.0605,137.936
8347,0.637,2020,0.10100,['MAMAMOO'],0.634,211280,0.858,0,4BZXVFYCb76Q0Klojq4piV,0.000009,4,0.2580,-2.226,0,AYA,76,2020-11-03,0.0809,91.688
8348,0.195,2020,0.00998,['Eminem'],0.671,337147,0.623,1,5SiZJoLXp3WOl3J4C8IK0d,0.000008,2,0.6430,-7.161,1,Darkness,70,2020-01-17,0.3080,75.055
8349,0.642,2020,0.13200,"['KEVVO', 'J Balvin']",0.856,189507,0.721,1,7HmnJHfs0BkFzX4x8j0hkl,0.004710,7,0.1820,-4.928,1,Billetes Azules (with J Balvin),74,2020-10-16,0.1080,94.991

In [43]:
df.shape

(8350, 19)

In [22]:
# selecting the relevant features for recommendation

selected_features = ['acousticness','artists','danceability','energy','instrumentalness','liveness','loudness','mode','tempo','release_date']
selected_features

['acousticness',
 'artists',
 'danceability',
 'energy',
 'instrumentalness',
 'liveness',
 'loudness',
 'mode',
 'tempo',
 'release_date']

In [23]:
# replacing the null valuess with null string

for feature in selected_features:
  df[feature] = df[feature].fillna('')

In [24]:
# combining all the selected features

combined_features = (
    df['acousticness'].astype(str) + ' ' +
    df['artists'] + ' ' +
    df['danceability'].astype(str) + ' ' +
    df['energy'].astype(str) + ' ' +
    df['instrumentalness'].astype(str) + ' ' +
    df['liveness'].astype(str) + ' ' +
    df['loudness'].astype(str) + ' ' +
    df['mode'].astype(str) + ' ' +
    df['popularity'].astype(str) + ' ' +
    df['tempo'].astype(str) + ' ' +
    df['release_date']
)

In [25]:
print(combined_features)

15606     0.00239 ['Coldplay'] 0.429 0.6609999999999999 ...
15607     0.143 ['OutKast'] 0.843 0.8059999999999999 0.0...
15608     0.00958 ['Linkin Park'] 0.556 0.86400000000000...
15609     0.00664 ['3 Doors Down'] 0.545 0.865 1.1e-05 0...
15610     0.0302 ['Eminem'] 0.949 0.6609999999999999 0.0...
                                ...
170648    0.0846 ['Anuel AA', 'Daddy Yankee', 'KAROL G',...
170649    0.206 ['Ashnikko'] 0.7170000000000001 0.753 0....
170650    0.101 ['MAMAMOO'] 0.634 0.858 8.56e-06 0.258 -...
170651    0.00998 ['Eminem'] 0.6709999999999999 0.623 7....
170652    0.132 ['KEVVO', 'J Balvin'] 0.856 0.721 0.0047...
Length: 8350, dtype: object

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [27]:
# converting the data to feature vectors

vectorizer = TfidfVectorizer()

In [28]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [29]:
print(feature_vectors)

  (0, 2205)	0.1221370901526142
  (0, 1865)	0.14785811645642272
  (0, 2423)	0.23902763672715147
  (0, 2795)	0.33121441153347725
  (0, 2366)	0.24685223368276613
  (0, 3832)	0.2135752325323326
  (0, 2501)	0.2817856781888597
  (0, 2516)	0.27222822847158856
  (0, 22)	0.36964503136622073
  (0, 3413)	0.2685680099195653
  (0, 2920)	0.2956168515971979
  (0, 4993)	0.2940204141143842
  (0, 658)	0.39206884218910687
  (1, 2668)	0.2315107381761039
  (1, 4089)	0.3008153299240961
  (1, 4071)	0.22815910638505144
  (1, 3737)	0.22364803538059133
  (1, 4084)	0.380087963326706
  (1, 1946)	0.3533351795394586
  (1, 3750)	0.31852128120779
  (1, 3838)	0.29344605997678047
  (1, 7057)	0.39384078526220484
  (1, 2297)	0.23747643935127524
  (1, 2205)	0.13301169976706267
  (1, 2423)	0.26030972420134973
  :	:
  (8348, 3197)	0.33564621579519727
  (8348, 1699)	0.30051905223705
  (8348, 3378)	0.2876175504167758
  (8348, 3621)	0.1889303555614731
  (8348, 3437)	0.28577375243532904
  (8348, 3336)	0.2822898757161034
  (8348, 2361)	0.19667907417381253
  (8348, 1189)	0.1392443904665892
  (8348, 3507)	0.16948659245975106
  (8348, 1754)	0.1173346992901226
  (8348, 5379)	0.283136940478661
  (8349, 6216)	0.3971187563517598
  (8349, 848)	0.3971187563517598
  (8349, 2447)	0.12281403482313022
  (8349, 4501)	0.26973940831452514
  (8349, 3559)	0.2859212636386915
  (8349, 3869)	0.29249565818207046
  (8349, 2382)	0.2767019726010009
  (8349, 2273)	0.23091518549352757
  (8349, 4045)	0.29746724872114966
  (8349, 4197)	0.2750609985760768
  (8349, 2331)	0.19969120101932727
  (8349, 3597)	0.17641055548273973
  (8349, 4071)	0.2192665358131936
  (8349, 2205)	0.12782752830968858

In [30]:
# getting the similarity scores using cosine similarity

similarity = cosine_similarity(feature_vectors)

In [35]:
similarity.shape

(8350, 8350)

In [44]:
df[df['name']=='Yellow']

,valence,year,acousticness,artists,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,loudness,mode,name,popularity,release_date,speechiness,tempo
0,0.285,2000,0.00239,['Coldplay'],0.429,266773,0.661,0,3AJwUDP919kvQ9QcozQPxg,0.000121,11,0.234,-7.227,1,Yellow,84,2000-07-10,0.0281,173.372

In [54]:
def recommendation(song_df):
    idx = df[df['name'] == song_df].index[0]
    distances = sorted(list(enumerate(similarity[idx])),reverse=True,key=lambda x:x[1])
    
    songs = []
    for m_id in distances[1:6]:
        songs.append(df.iloc[m_id[0]]['name'])
        
    return songs

In [55]:
recommendation('Trouble')

['Sparks', 'Shiver', "Don't Panic", 'Yellow', 'Always in My Head']

In [47]:
import pickle
pickle.dump(similarity,open('similarity.pkl','wb'))

In [48]:
pickle.dump(df,open('df.pkl','wb'))